#ifndef ZMK_LAYOUT_SHIFT_H
#define ZMK_LAYOUT_SHIFT_H

#include <dt-bindings/zmk/modifiers.h>

#define LAYOUT_SHIFT_OPTIONAL_SHIFT  (MOD_LSFT | MOD_RSFT)
#define LAYOUT_SHIFT_OPTIONAL_CTRL   (MOD_LCTL | MOD_RCTL)
#define LAYOUT_SHIFT_OPTIONAL_ALT    (MOD_LALT | MOD_RALT)
#define LAYOUT_SHIFT_OPTIONAL_GUI    (MOD_LGUI | MOD_RGUI)
#define LAYOUT_SHIFT_OPTIONAL_ALL    0xFF
#define LAYOUT_SHIFT_OPTIONAL_NONE   0

#endif
